apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: project
spec:
  selector:
    app: project
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
  type: {{ .Values.service.type}}