apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-html
  namespace: project
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! I got deployed in Environment using Helm Chart </h1>
    </html
