# mon-projet-chart/templates/database-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: project
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password     
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: my-secret
